## 🚢 Titanic Survival Analysis — Insight-Driven Visualization

📦 Dataset: Seaborn Built-in Titanic \
🎯 Goal: Uncover survival patterns via 13 plot types \
👤 Author: D_Manglam

### 🔍 Phase 1 — Setup + Raw Exploration

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = sns.load_dataset("titanic")

In [3]:
df.shape

(891, 15)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [5]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [9]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [11]:
df["deck"].shape[0]

891

In [14]:
deck_null_percentage = round((df["deck"].isnull().sum()/df["deck"].shape[0])*100,2)
print(deck_null_percentage)

77.22

In [15]:
df[["alive", "survived"]]

    alive  survived
0      no         0
1     yes         1
2     yes         1
3     yes         1
4      no         0
..    ...       ...
886    no         0
887   yes         1
888    no         0
889   yes         1
890    no         0

[891 rows x 2 columns]

In [16]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [19]:
df[["embarked", "embark_town"]]

    embarked  embark_town
0          S  Southampton
1          C    Cherbourg
2          S  Southampton
3          S  Southampton
4          S  Southampton
..       ...          ...
886        S  Southampton
887        S  Southampton
888        S  Southampton
889        C    Cherbourg
890        Q   Queenstown

[891 rows x 2 columns]

### 1. Drop high-null and redundant columns

In [21]:
df.drop(columns=["deck", "alive", "embark_town"], inplace=True)

In [40]:
df.dropna(inplace=True)

In [22]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'alone'],
      dtype='str')

### 2. Fill age nulls with median

In [33]:
df["age"] = df["age"].fillna(df["age"].median())

In [34]:
print(df["age"].isnull().sum())

0

### 3. Confirm shape

In [41]:
df.shape

(889, 12)

### 4. Save to `processed/`

In [42]:
df.to_csv('../data/processed/titanic_cleaned.csv', index=False)

In [37]:
import os
os.getcwd()

'D:\\Data_Science\\01_Practice\\07_Data_Visualization\\notebooks'

In [43]:
print(os.path.exists('../data/processed/'))

True