In [2]:
%pip install "numpy<2"

Collecting numpy<2
  Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
    --------------------------------------- 0.3/15.5 MB ? eta -:--:--
    --------------------------------------- 0.3/15.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/15.5 MB 670.4 kB/s eta 0:00:23
   - -------------------------------------- 0.5/15.5 MB 670.4 kB/s eta 0:00:23
   - -------------------------------------- 0.5/15.5 MB 670.4 kB/s eta 0:00:23
   - -------------------------------------- 0.5/15.5 MB 670.4 kB/s eta 0:00:23
   - -------------------------------------- 0.5/15.5 MB 670.4 kB/s eta 0:00:23
   - -------------------------------------- 0.5/15.5 MB 670.4 kB/s eta 0:00:23
   - -------------------------------------- 0.5/15.5 MB 670.4 kB/s eta 0:00:23
   -- ------------------------------------- 0.8/15.5 MB 286.8 kB/s eta 0:00:52
   -- ------------------------------------- 0.8/15.5 MB 286.8 kB/s eta 0:00:52
   -- ------------------------------------- 0.8/15.5 MB 286.8 kB/s eta 0:00:52
   -- ------------------------------------- 0.8/15.5 MB 286.8 kB/s eta 0:00:52
   -- ------------------------------------- 0.8/15.5 MB 286.8 kB/s eta 0:00:52
   -- ------------------------------------- 0.8/15.5 MB 286.8 kB/s eta 0:00:52
   -- ------------------------------------- 1.0/15.5 MB 253.0 kB/s eta 0:00:58
   --- ------------------------------------ 1.3/15.5 MB 309.2 kB/s eta 0:00:46
   --- ------------------------------------ 1.3/15.5 MB 309.2 kB/s eta 0:00:46
   ---- ----------------------------------- 1.6/15.5 MB 355.5 kB/s eta 0:00:40
   ---- ----------------------------------- 1.6/15.5 MB 355.5 kB/s eta 0:00:40
   ---- ----------------------------------- 1.8/15.5 MB 390.2 kB/s eta 0:00:36
   ---- ----------------------------------- 1.8/15.5 MB 390.2 kB/s eta 0:00:36
   ----- ---------------------------------- 2.1/15.5 MB 410.6 kB/s eta 0:00:33
   ------ --------------------------------- 2.4/15.5 MB 441.5 kB/s eta 0:00:30
   ------ --------------------------------- 2.6/15.5 MB 470.4 kB/s eta 0:00:28
   ------ --------------------------------- 2.6/15.5 MB 470.4 kB/s eta 0:00:28
   ------- -------------------------------- 2.9/15.5 MB 483.5 kB/s eta 0:00:27
   -------- ------------------------------- 3.1/15.5 MB 507.0 kB/s eta 0:00:25
   -------- ------------------------------- 3.1/15.5 MB 507.0 kB/s eta 0:00:25
   -------- ------------------------------- 3.4/15.5 MB 520.2 kB/s eta 0:00:24
   --------- ------------------------------ 3.7/15.5 MB 538.5 kB/s eta 0:00:22
   --------- ------------------------------ 3.7/15.5 MB 538.5 kB/s eta 0:00:22
   --------- ------------------------------ 3.7/15.5 MB 538.5 kB/s eta 0:00:22
   ---------- ----------------------------- 3.9/15.5 MB 541.2 kB/s eta 0:00:22
   ---------- ----------------------------- 3.9/15.5 MB 541.2 kB/s eta 0:00:22
   ---------- ----------------------------- 4.2/15.5 MB 534.3 kB/s eta 0:00:22
   ----------- ---------------------------- 4.5/15.5 MB 565.1 kB/s eta 0:00:20
   ----------- ---------------------------- 4.5/15.5 MB 565.1 kB/s eta 0:00:20
   ------------ --------------------------- 4.7/15.5 MB 559.2 kB/s eta 0:00:20
   ------------ --------------------------- 4.7/15.5 MB 559.2 kB/s eta 0:00:20
   ------------ --------------------------- 4.7/15.5 MB 559.2 kB/s eta 0:00:20
   ------------ --------------------------- 5.0/15.5 MB 554.1 kB/s eta 0:00:20
   ------------ --------------------------- 5.0/15.5 MB 554.1 kB/s eta 0:00:20
   ------------ --------------------------- 5.0/15.5 MB 554.1 kB/s eta 0:00:20
   ------------ --------------------------- 5.0/15.5 MB 554.1 kB/s eta 0:00:20
   ------------- -------------------------- 5.2/15.5 MB 529.5 kB/s eta 0:00:20
   ------------- -------------------------- 5.2/15.5 MB 529.5 kB/s eta 0:00:20
   -------------- ------------------------- 5.5/15.5 MB 533.5 kB/s eta 0:00:19
   -------------- ------------------------- 5.5/15.5 MB 533.5 kB/s eta 0:00:19
   -------------- ------------------------- 5.5/15.5 MB 533.5 kB/s eta 0:00:19
   -------------- ------------------------- 5.8/15.5 MB 525.8 kB/s eta 0:00:19
   -------------- ------------------------- 5.8/15.5 MB 525.8 kB/s eta 0:00:19
   -------------- ------------------------- 5.8/15.5 MB 525.8 kB/s eta 0:00:19
   --------------- ------------------------ 6.0/15.5 MB 519.8 kB/s eta 0:00:19
   --------------- ------------------------ 6.0/15.5 MB 519.8 kB/s eta 0:00:19
   --------------- ------------------------ 6.0/15.5 MB 519.8 kB/s eta 0:00:19
   ---------------- ----------------------- 6.3/15.5 MB 515.9 kB/s eta 0:00:18
   ---------------- ----------------------- 6.3/15.5 MB 515.9 kB/s eta 0:00:18
   ---------------- ----------------------- 6.3/15.5 MB 515.9 kB/s eta 0:00:18
   ---------------- ----------------------- 6.6/15.5 MB 511.6 kB/s eta 0:00:18
   ---------------- ----------------------- 6.6/15.5 MB 511.6 kB/s eta 0:00:18
   ---------------- ----------------------- 6.6/15.5 MB 511.6 kB/s eta 0:00:18
   ---------------- ----------------------- 6.6/15.5 MB 511.6 kB/s eta 0:00:18
   ----------------- ---------------------- 6.8/15.5 MB 499.9 kB/s eta 0:00:18
   ----------------- ---------------------- 6.8/15.5 MB 499.9 kB/s eta 0:00:18
   ----------------- ---------------------- 6.8/15.5 MB 499.9 kB/s eta 0:00:18
   ------------------ --------------------- 7.1/15.5 MB 495.1 kB/s eta 0:00:18
   ------------------ --------------------- 7.1/15.5 MB 495.1 kB/s eta 0:00:18
   ------------------ --------------------- 7.1/15.5 MB 495.1 kB/s eta 0:00:18
   ------------------ --------------------- 7.1/15.5 MB 495.1 kB/s eta 0:00:18
   ------------------ --------------------- 7.3/15.5 MB 487.1 kB/s eta 0:00:17
   ------------------ --------------------- 7.3/15.5 MB 487.1 kB/s eta 0:00:17
   ------------------ --------------------- 7.3/15.5 MB 487.1 kB/s eta 0:00:17
   ------------------ --------------------- 7.3/15.5 MB 487.1 kB/s eta 0:00:17
   ------------------- -------------------- 7.6/15.5 MB 477.9 kB/s eta 0:00:17
   ------------------- -------------------- 7.6/15.5 MB 477.9 kB/s eta 0:00:17
   ------------------- -------------------- 7.6/15.5 MB 477.9 kB/s eta 0:00:17
   ------------------- -------------------- 7.6/15.5 MB 477.9 kB/s eta 0:00:17
   -------------------- ------------------- 7.9/15.5 MB 470.1 kB/s eta 0:00:17
   -------------------- ------------------- 7.9/15.5 MB 470.1 kB/s eta 0:00:17
   -------------------- ------------------- 7.9/15.5 MB 470.1 kB/s eta 0:00:17
   -------------------- ------------------- 7.9/15.5 MB 470.1 kB/s eta 0:00:17
   -------------------- ------------------- 8.1/15.5 MB 464.7 kB/s eta 0:00:16
   -------------------- ------------------- 8.1/15.5 MB 464.7 kB/s eta 0:00:16
   -------------------- ------------------- 8.1/15.5 MB 464.7 kB/s eta 0:00:16
   --------------------- ------------------ 8.4/15.5 MB 459.0 kB/s eta 0:00:16
   --------------------- ------------------ 8.4/15.5 MB 459.0 kB/s eta 0:00:16
   --------------------- ------------------ 8.4/15.5 MB 459.0 kB/s eta 0:00:16
   ---------------------- ----------------- 8.7/15.5 MB 457.3 kB/s eta 0:00:16
   ---------------------- ----------------- 8.7/15.5 MB 457.3 kB/s eta 0:00:16
   ---------------------- ----------------- 8.7/15.5 MB 457.3 kB/s eta 0:00:16
   ---------------------- ----------------- 8.7/15.5 MB 457.3 kB/s eta 0:00:16
   ---------------------- ----------------- 8.9/15.5 MB 451.9 kB/s eta 0:00:15
   ---------------------- ----------------- 8.9/15.5 MB 451.9 kB/s eta 0:00:15
   ---------------------- ----------------- 8.9/15.5 MB 451.9 kB/s eta 0:00:15
   ----------------------- ---------------- 9.2/15.5 MB 450.6 kB/s eta 0:00:15
   ----------------------- ---------------- 9.2/15.5 MB 450.6 kB/s eta 0:00:15
   ----------------------- ---------------- 9.2/15.5 MB 450.6 kB/s eta 0:00:15
   ------------------------ --------------- 9.4/15.5 MB 449.3 kB/s eta 0:00:14
   ------------------------ --------------- 9.4/15.5 MB 449.3 kB/s eta 0:00:14
   ------------------------ --------------- 9.4/15.5 MB 449.3 kB/s eta 0:00:14
   ------------------------- -------------- 9.7/15.5 MB 449.7 kB/s eta 0:00:13
   ------------------------- -------------- 9.7/15.5 MB 449.7 kB/s eta 0:00:13
   ------------------------- -------------- 9.7/15.5 MB 449.7 kB/s eta 0:00:13
   ------------------------- -------------- 10.0/15.5 MB 449.5 kB/s eta 0:00:13
   -------------------------- ------------- 10.2/15.5 MB 454.7 kB/s eta 0:00:12
   -------------------------- ------------- 10.2/15.5 MB 454.7 kB/s eta 0:00:12
   -------------------------- ------------- 10.2/15.5 MB 454.7 kB/s eta 0:00:12
   -------------------------- ------------- 10.2/15.5 MB 454.7 kB/s eta 0:00:12
   --------------------------- ------------ 10.5/15.5 MB 450.0 kB/s eta 0:00:12
   --------------------------- ------------ 10.5/15.5 MB 450.0 kB/s eta 0:00:12
   --------------------------- ------------ 10.5/15.5 MB 450.0 kB/s eta 0:00:12
   --------------------------- ------------ 10.5/15.5 MB 450.0 kB/s eta 0:00:12
   --------------------------- ------------ 10.7/15.5 MB 448.6 kB/s eta 0:00:11
   --------------------------- ------------ 10.7/15.5 MB 448.6 kB/s eta 0:00:11
   --------------------------- ------------ 10.7/15.5 MB 448.6 kB/s eta 0:00:11
   ---------------------------- ----------- 11.0/15.5 MB 445.5 kB/s eta 0:00:11
   ---------------------------- ----------- 11.0/15.5 MB 445.5 kB/s eta 0:00:11
   ---------------------------- ----------- 11.0/15.5 MB 445.5 kB/s eta 0:00:11
   ---------------------------- ----------- 11.0/15.5 MB 445.5 kB/s eta 0:00:11
   ---------------------------- ----------- 11.0/15.5 MB 445.5 kB/s eta 0:00:11
   ---------------------------- ----------- 11.0/15.5 MB 445.5 kB/s eta 0:00:11
   ----------------------------- ---------- 11.3/15.5 MB 433.6 kB/s eta 0:00:10
   ----------------------------- ---------- 11.3/15.5 MB 433.6 kB/s eta 0:00:10
   ----------------------------- ---------- 11.3/15.5 MB 433.6 kB/s eta 0:00:10
   ----------------------------- ---------- 11.3/15.5 MB 433.6 kB/s eta 0:00:10
   ----------------------------- ---------- 11.3/15.5 MB 433.6 kB/s eta 0:00:10
   ----------------------------- ---------- 11.3/15.5 MB 433.6 kB/s eta 0:00:10
   ----------------------------- ---------- 11.5/15.5 MB 424.9 kB/s eta 0:00:10
   ----------------------------- ---------- 11.5/15.5 MB 424.9 kB/s eta 0:00:10
   ----------------------------- ---------- 11.5/15.5 MB 424.9 kB/s eta 0:00:10
   ----------------------------- ---------- 11.5/15.5 MB 424.9 kB/s eta 0:00:10
   ----------------------------- ---------- 11.5/15.5 MB 424.9 kB/s eta 0:00:10
   ----------------------------- ---------- 11.5/15.5 MB 424.9 kB/s eta 0:00:10
   ----------------------------- ---------- 11.5/15.5 MB 424.9 kB/s eta 0:00:10
   ----------------------------- ---------- 11.5/15.5 MB 424.9 kB/s eta 0:00:10
   ------------------------------ --------- 11.8/15.5 MB 407.8 kB/s eta 0:00:10
   ------------------------------ --------- 11.8/15.5 MB 407.8 kB/s eta 0:00:10
   ------------------------------ --------- 11.8/15.5 MB 407.8 kB/s eta 0:00:10
   ------------------------------ --------- 11.8/15.5 MB 407.8 kB/s eta 0:00:10
   ------------------------------ --------- 11.8/15.5 MB 407.8 kB/s eta 0:00:10
   ------------------------------ --------- 11.8/15.5 MB 407.8 kB/s eta 0:00:10
   ------------------------------ --------- 11.8/15.5 MB 407.8 kB/s eta 0:00:10
   ------------------------------ --------- 11.8/15.5 MB 407.8 kB/s eta 0:00:10
   ------------------------------ --------- 11.8/15.5 MB 407.8 kB/s eta 0:00:10
   ------------------------------- -------- 12.1/15.5 MB 388.3 kB/s eta 0:00:09
   ------------------------------- -------- 12.1/15.5 MB 388.3 kB/s eta 0:00:09
   ------------------------------- -------- 12.1/15.5 MB 388.3 kB/s eta 0:00:09
   ------------------------------- -------- 12.1/15.5 MB 388.3 kB/s eta 0:00:09
   ------------------------------- -------- 12.1/15.5 MB 388.3 kB/s eta 0:00:09
   ------------------------------- -------- 12.1/15.5 MB 388.3 kB/s eta 0:00:09
   ------------------------------- -------- 12.1/15.5 MB 388.3 kB/s eta 0:00:09
   ------------------------------- -------- 12.1/15.5 MB 388.3 kB/s eta 0:00:09
   ------------------------------- -------- 12.1/15.5 MB 388.3 kB/s eta 0:00:09
   ------------------------------- -------- 12.1/15.5 MB 388.3 kB/s eta 0:00:09
   ------------------------------- -------- 12.3/15.5 MB 387.4 kB/s eta 0:00:09
   ------------------------------- -------- 12.3/15.5 MB 387.4 kB/s eta 0:00:09
   ------------------------------- -------- 12.3/15.5 MB 387.4 kB/s eta 0:00:09
   ------------------------------- -------- 12.3/15.5 MB 387.4 kB/s eta 0:00:09
   ------------------------------- -------- 12.3/15.5 MB 387.4 kB/s eta 0:00:09
   ------------------------------- -------- 12.3/15.5 MB 387.4 kB/s eta 0:00:09
   ------------------------------- -------- 12.3/15.5 MB 387.4 kB/s eta 0:00:09
   ------------------------------- -------- 12.3/15.5 MB 387.4 kB/s eta 0:00:09
   ------------------------------- -------- 12.3/15.5 MB 387.4 kB/s eta 0:00:09
   -------------------------------- ------- 12.6/15.5 MB 359.9 kB/s eta 0:00:09
   -------------------------------- ------- 12.6/15.5 MB 359.9 kB/s eta 0:00:09
   -------------------------------- ------- 12.6/15.5 MB 359.9 kB/s eta 0:00:09
   -------------------------------- ------- 12.6/15.5 MB 359.9 kB/s eta 0:00:09
   -------------------------------- ------- 12.6/15.5 MB 359.9 kB/s eta 0:00:09
   -------------------------------- ------- 12.6/15.5 MB 359.9 kB/s eta 0:00:09
   --------------------------------- ------ 12.8/15.5 MB 334.8 kB/s eta 0:00:08
   --------------------------------- ------ 12.8/15.5 MB 334.8 kB/s eta 0:00:08
   --------------------------------- ------ 12.8/15.5 MB 334.8 kB/s eta 0:00:08
   --------------------------------- ------ 12.8/15.5 MB 334.8 kB/s eta 0:00:08
   --------------------------------- ------ 12.8/15.5 MB 334.8 kB/s eta 0:00:08
   --------------------------------- ------ 12.8/15.5 MB 334.8 kB/s eta 0:00:08
   --------------------------------- ------ 13.1/15.5 MB 309.4 kB/s eta 0:00:08
   --------------------------------- ------ 13.1/15.5 MB 309.4 kB/s eta 0:00:08
   --------------------------------- ------ 13.1/15.5 MB 309.4 kB/s eta 0:00:08
   --------------------------------- ------ 13.1/15.5 MB 309.4 kB/s eta 0:00:08
   --------------------------------- ------ 13.1/15.5 MB 309.4 kB/s eta 0:00:08
   --------------------------------- ------ 13.1/15.5 MB 309.4 kB/s eta 0:00:08
   --------------------------------- ------ 13.1/15.5 MB 309.4 kB/s eta 0:00:08
   --------------------------------- ------ 13.1/15.5 MB 309.4 kB/s eta 0:00:08
   ---------------------------------- ----- 13.4/15.5 MB 283.6 kB/s eta 0:00:08
   ---------------------------------- ----- 13.4/15.5 MB 283.6 kB/s eta 0:00:08
   ---------------------------------- ----- 13.4/15.5 MB 283.6 kB/s eta 0:00:08
   ---------------------------------- ----- 13.4/15.5 MB 283.6 kB/s eta 0:00:08
   ---------------------------------- ----- 13.4/15.5 MB 283.6 kB/s eta 0:00:08
   ---------------------------------- ----- 13.4/15.5 MB 283.6 kB/s eta 0:00:08
   ---------------------------------- ----- 13.4/15.5 MB 283.6 kB/s eta 0:00:08
   ---------------------------------- ----- 13.4/15.5 MB 283.6 kB/s eta 0:00:08
   ---------------------------------- ----- 13.4/15.5 MB 283.6 kB/s eta 0:00:08
   ----------------------------------- ---- 13.6/15.5 MB 266.0 kB/s eta 0:00:08
   ----------------------------------- ---- 13.6/15.5 MB 266.0 kB/s eta 0:00:08
   ----------------------------------- ---- 13.6/15.5 MB 266.0 kB/s eta 0:00:08
   ----------------------------------- ---- 13.6/15.5 MB 266.0 kB/s eta 0:00:08
   ----------------------------------- ---- 13.6/15.5 MB 266.0 kB/s eta 0:00:08
   ----------------------------------- ---- 13.6/15.5 MB 266.0 kB/s eta 0:00:08
   ----------------------------------- ---- 13.6/15.5 MB 266.0 kB/s eta 0:00:08
   ----------------------------------- ---- 13.6/15.5 MB 266.0 kB/s eta 0:00:08
   ----------------------------------- ---- 13.6/15.5 MB 266.0 kB/s eta 0:00:08
   ----------------------------------- ---- 13.6/15.5 MB 266.0 kB/s eta 0:00:08
   ----------------------------------- ---- 13.9/15.5 MB 247.4 kB/s eta 0:00:07
   ----------------------------------- ---- 13.9/15.5 MB 247.4 kB/s eta 0:00:07
   ----------------------------------- ---- 13.9/15.5 MB 247.4 kB/s eta 0:00:07
   ----------------------------------- ---- 13.9/15.5 MB 247.4 kB/s eta 0:00:07
   ----------------------------------- ---- 13.9/15.5 MB 247.4 kB/s eta 0:00:07
   ------------------------------------ --- 14.2/15.5 MB 240.8 kB/s eta 0:00:06
   ------------------------------------ --- 14.2/15.5 MB 240.8 kB/s eta 0:00:06
   ------------------------------------ --- 14.2/15.5 MB 240.8 kB/s eta 0:00:06
   ------------------------------------ --- 14.2/15.5 MB 240.8 kB/s eta 0:00:06
   ------------------------------------ --- 14.2/15.5 MB 240.8 kB/s eta 0:00:06
   ------------------------------------ --- 14.2/15.5 MB 240.8 kB/s eta 0:00:06
   ------------------------------------- -- 14.4/15.5 MB 237.4 kB/s eta 0:00:05
   ------------------------------------- -- 14.4/15.5 MB 237.4 kB/s eta 0:00:05
   ------------------------------------- -- 14.4/15.5 MB 237.4 kB/s eta 0:00:05
   ------------------------------------- -- 14.4/15.5 MB 237.4 kB/s eta 0:00:05
   ------------------------------------- -- 14.4/15.5 MB 237.4 kB/s eta 0:00:05
   ------------------------------------- -- 14.4/15.5 MB 237.4 kB/s eta 0:00:05
   ------------------------------------- -- 14.7/15.5 MB 231.9 kB/s eta 0:00:04
   ------------------------------------- -- 14.7/15.5 MB 231.9 kB/s eta 0:00:04
   ------------------------------------- -- 14.7/15.5 MB 231.9 kB/s eta 0:00:04
   ------------------------------------- -- 14.7/15.5 MB 231.9 kB/s eta 0:00:04
   ------------------------------------- -- 14.7/15.5 MB 231.9 kB/s eta 0:00:04
   ------------------------------------- -- 14.7/15.5 MB 231.9 kB/s eta 0:00:04
   -------------------------------------- - 14.9/15.5 MB 228.5 kB/s eta 0:00:03
   -------------------------------------- - 14.9/15.5 MB 228.5 kB/s eta 0:00:03
   -------------------------------------- - 14.9/15.5 MB 228.5 kB/s eta 0:00:03
   -------------------------------------- - 14.9/15.5 MB 228.5 kB/s eta 0:00:03
   -------------------------------------- - 14.9/15.5 MB 228.5 kB/s eta 0:00:03
   -------------------------------------- - 14.9/15.5 MB 228.5 kB/s eta 0:00:03
   -------------------------------------- - 14.9/15.5 MB 228.5 kB/s eta 0:00:03
   -------------------------------------- - 14.9/15.5 MB 228.5 kB/s eta 0:00:03
   -------------------------------------- - 14.9/15.5 MB 228.5 kB/s eta 0:00:03
   -------------------------------------- - 14.9/15.5 MB 228.5 kB/s eta 0:00:03
   -------------------------------------- - 14.9/15.5 MB 228.5 kB/s eta 0:00:03
   -------------------------------------- - 14.9/15.5 MB 228.5 kB/s eta 0:00:03
   ---------------------------------------  15.2/15.5 MB 204.6 kB/s eta 0:00:02
   ---------------------------------------  15.2/15.5 MB 204.6 kB/s eta 0:00:02
   ---------------------------------------  15.2/15.5 MB 204.6 kB/s eta 0:00:02
   ---------------------------------------  15.2/15.5 MB 204.6 kB/s eta 0:00:02
   ---------------------------------------  15.2/15.5 MB 204.6 kB/s eta 0:00:02
   ---------------------------------------  15.2/15.5 MB 204.6 kB/s eta 0:00:02
   ---------------------------------------  15.2/15.5 MB 204.6 kB/s eta 0:00:02
   ---------------------------------------  15.2/15.5 MB 204.6 kB/s eta 0:00:02

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\mangl\AppData\Roaming\Python\Python312\site-packages\~-mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\mangl\AppData\Roaming\Python\Python312\site-packages\~-mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.3 requires scipy<1.14.0,>=1.7.0, but you have scipy 1.15.2 which is incompatible.

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "A": [1,2,np.nan,4,5],
    "B": [np.nan,2,3,4,5],
    "C": [1,2,3,np.nan, np.nan],
    "D": [1,np.nan,np.nan,np.nan,5]
}

In [3]:
df = pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [5]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [7]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [8]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [10]:
df.dropna(thresh=4)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [11]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [12]:
df.dropna(thresh=4)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [15]:
print(df["A"].isna().sum())
print(df["B"].isna().sum())
print(df["C"].isna().sum())
print(df["D"].isna().sum())
values = {"A":0, "B":100, "C":300, "D":500}
df.fillna(value=values)

1
1
2
3

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  500.0
2  0.0    3.0    3.0  500.0
3  4.0    4.0  300.0  500.0
4  5.0    5.0  300.0    5.0

In [16]:
df.fillna(value=df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0

In [20]:
employees = pd.DataFrame({
    "employee_id": [1,2,3,4,5],
    "name": ["Ram", "Mohan", "Bhola", "Chota", "Bulbul"],
    "department": ["HR", "IT", "Finance","IT", "HR"],
})

salaries = pd.DataFrame({
    "employee_id": [1,2,3,6,7],
    "salary": [60000, 80000, 65000, 70000, 90000],
    "bonus": [5000, 10000, 7000, 8000, 12000]
})

print(employees)
print()
print(salaries)

   employee_id    name department
0            1     Ram         HR
1            2   Mohan         IT
2            3   Bhola    Finance
3            4   Chota         IT
4            5  Bulbul         HR

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [23]:
pd.merge(employees, salaries, on="employee_id", how="inner")

   employee_id   name department  salary  bonus
0            1    Ram         HR   60000   5000
1            2  Mohan         IT   80000  10000
2            3  Bhola    Finance   65000   7000

In [24]:
pd.merge(employees, salaries, on="employee_id", how="outer")

   employee_id    name department   salary    bonus
0            1     Ram         HR  60000.0   5000.0
1            2   Mohan         IT  80000.0  10000.0
2            3   Bhola    Finance  65000.0   7000.0
3            4   Chota         IT      NaN      NaN
4            5  Bulbul         HR      NaN      NaN
5            6     NaN        NaN  70000.0   8000.0
6            7     NaN        NaN  90000.0  12000.0

In [25]:
pd.merge(employees, salaries, on="employee_id", how="left")

   employee_id    name department   salary    bonus
0            1     Ram         HR  60000.0   5000.0
1            2   Mohan         IT  80000.0  10000.0
2            3   Bhola    Finance  65000.0   7000.0
3            4   Chota         IT      NaN      NaN
4            5  Bulbul         HR      NaN      NaN

In [26]:
pd.merge(employees, salaries, on="employee_id", how="right")

   employee_id   name department  salary  bonus
0            1    Ram         HR   60000   5000
1            2  Mohan         IT   80000  10000
2            3  Bhola    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [27]:
df1 = pd.DataFrame({
    "A": ["A0", "A1", "A2"],
    "B": ["B0", "B1", "B2"],
    "C": ["C0", "C1", "C2"],
})
df2 = pd.DataFrame({
    "A": ["A3", "A4", "A5"],
    "B": ["B3", "B4", "B5"],
    "C": ["C3", "C4", "C5"],
})

print(df1)
print()
print(df2)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [31]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [32]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [33]:
df3 = pd.DataFrame({
    "name": ["Ram", "Mohan", "Bhola"],
}, index=[1,2,3])
df4 = pd.DataFrame({
    "score": [85,90,75],
}, index=[2,3,4])

In [36]:
df3.join(df4, how='outer')

    name  score
1    Ram    NaN
2  Mohan   85.0
3  Bhola   90.0
4    NaN   75.0

In [39]:
data = {
    "Category": ["A", "B", "A", "B", "A", "B", "A", "B"],
    "Store": ["51", "51", "52", "52", "51", "52", "52", "51"],
    "Sales": [100,200,150,250,120,100,200,300],
    "Quantity": [10,15,12,18,8,20,15,25],
    "Date":pd.date_range("01-03-2026", periods=8)
}

df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    51    100        10 2026-01-03
1        B    51    200        15 2026-01-04
2        A    52    150        12 2026-01-05
3        B    52    250        18 2026-01-06
4        A    51    120         8 2026-01-07
5        B    52    100        20 2026-01-08
6        A    52    200        15 2026-01-09
7        B    51    300        25 2026-01-10

In [ ]:
cat = df.groupby("Category")["Sales"].sum()
cat

Category
A    570
B    850
Name: Sales, dtype: int64

In [47]:
cat = df.groupby(["Category", "Store"])["Sales"].sum()
cat

Category  Store
A         51       220
          52       350
B         51       500
          52       350
Name: Sales, dtype: int64

In [48]:
df["Sales"].mean()

177.5

In [54]:
df["Sales"].agg(["mean","median", "min"])
df["Sales"].stats()

AttributeError: 'Series' object has no attribute 'stats'